export interface EmojiCategory {
  name: string;
  emojis: { shortcode: string; emoji: string }[];
}

export interface TextSegment {
  type: 'text' | 'emoji';
  content: string;
}

// Hand-curated map of ~250 common emoji shortcodes to Unicode
export const EMOJI_SHORTCODES = new Map<string, string>([
  // Smileys & Emotion
  ['smile', '\u{1F604}'],
  ['laughing', '\u{1F606}'],
  ['blush', '\u{1F60A}'],
  ['smiley', '\u{1F603}'],
  ['grinning', '\u{1F600}'],
  ['grin', '\u{1F601}'],
  ['joy', '\u{1F602}'],
  ['rofl', '\u{1F923}'],
  ['relaxed', '\u{263A}\u{FE0F}'],
  ['wink', '\u{1F609}'],
  ['innocent', '\u{1F607}'],
  ['heart_eyes', '\u{1F60D}'],
  ['star_struck', '\u{1F929}'],
  ['kissing_heart', '\u{1F618}'],
  ['kissing', '\u{1F617}'],
  ['kissing_smiling_eyes', '\u{1F619}'],
  ['kissing_closed_eyes', '\u{1F61A}'],
  ['yum', '\u{1F60B}'],
  ['stuck_out_tongue', '\u{1F61B}'],
  ['stuck_out_tongue_winking_eye', '\u{1F61C}'],
  ['stuck_out_tongue_closed_eyes', '\u{1F61D}'],
  ['zany_face', '\u{1F92A}'],
  ['hugs', '\u{1F917}'],
  ['money_mouth_face', '\u{1F911}'],
  ['thinking', '\u{1F914}'],
  ['shushing_face', '\u{1F92B}'],
  ['zipper_mouth_face', '\u{1F910}'],
  ['raised_eyebrow', '\u{1F928}'],
  ['neutral_face', '\u{1F610}'],
  ['expressionless', '\u{1F611}'],
  ['no_mouth', '\u{1F636}'],
  ['smirk', '\u{1F60F}'],
  ['unamused', '\u{1F612}'],
  ['roll_eyes', '\u{1F644}'],
  ['grimacing', '\u{1F62C}'],
  ['lying_face', '\u{1F925}'],
  ['relieved', '\u{1F60C}'],
  ['pensive', '\u{1F614}'],
  ['sleepy', '\u{1F62A}'],
  ['drooling_face', '\u{1F924}'],
  ['sleeping', '\u{1F634}'],
  ['mask', '\u{1F637}'],
  ['nerd_face', '\u{1F913}'],
  ['sunglasses', '\u{1F60E}'],
  ['disguised_face', '\u{1F978}'],
  ['cowboy_hat_face', '\u{1F920}'],
  ['partying_face', '\u{1F973}'],
  ['confused', '\u{1F615}'],
  ['worried', '\u{1F61F}'],
  ['slightly_frowning_face', '\u{1F641}'],
  ['frowning_face', '\u{2639}\u{FE0F}'],
  ['open_mouth', '\u{1F62E}'],
  ['hushed', '\u{1F62F}'],
  ['astonished', '\u{1F632}'],
  ['flushed', '\u{1F633}'],
  ['pleading_face', '\u{1F97A}'],
  ['cry', '\u{1F622}'],
  ['sob', '\u{1F62D}'],
  ['scream', '\u{1F631}'],
  ['confounded', '\u{1F616}'],
  ['persevere', '\u{1F623}'],
  ['disappointed', '\u{1F61E}'],
  ['sweat', '\u{1F613}'],
  ['weary', '\u{1F629}'],
  ['tired_face', '\u{1F62B}'],
  ['yawning_face', '\u{1F971}'],
  ['triumph', '\u{1F624}'],
  ['rage', '\u{1F621}'],
  ['angry', '\u{1F620}'],
  ['cursing_face', '\u{1F92C}'],
  ['skull', '\u{1F480}'],
  ['skull_and_crossbones', '\u{2620}\u{FE0F}'],
  ['poop', '\u{1F4A9}'],
  ['clown_face', '\u{1F921}'],
  ['ghost', '\u{1F47B}'],
  ['alien', '\u{1F47D}'],
  ['robot', '\u{1F916}'],
  ['jack_o_lantern', '\u{1F383}'],
  ['smiley_cat', '\u{1F63A}'],
  ['heart_eyes_cat', '\u{1F63B}'],
  ['crying_cat_face', '\u{1F63F}'],
  ['see_no_evil', '\u{1F648}'],
  ['hear_no_evil', '\u{1F649}'],
  ['speak_no_evil', '\u{1F64A}'],

  // Hearts & love
  ['heart', '\u{2764}\u{FE0F}'],
  ['orange_heart', '\u{1F9E1}'],
  ['yellow_heart', '\u{1F49B}'],
  ['green_heart', '\u{1F49A}'],
  ['blue_heart', '\u{1F499}'],
  ['purple_heart', '\u{1F49C}'],
  ['black_heart', '\u{1F5A4}'],
  ['brown_heart', '\u{1F90E}'],
  ['white_heart', '\u{1F90D}'],
  ['broken_heart', '\u{1F494}'],
  ['sparkling_heart', '\u{1F496}'],
  ['two_hearts', '\u{1F495}'],
  ['revolving_hearts', '\u{1F49E}'],
  ['heartbeat', '\u{1F493}'],
  ['heartpulse', '\u{1F497}'],
  ['cupid', '\u{1F498}'],
  ['gift_heart', '\u{1F49D}'],
  ['kiss', '\u{1F48B}'],
  ['100', '\u{1F4AF}'],
  ['anger', '\u{1F4A2}'],
  ['boom', '\u{1F4A5}'],
  ['dizzy', '\u{1F4AB}'],
  ['sweat_drops', '\u{1F4A6}'],
  ['fire', '\u{1F525}'],
  ['star', '\u{2B50}'],
  ['star2', '\u{1F31F}'],
  ['sparkles', '\u{2728}'],
  ['zap', '\u{26A1}'],

  // People & Gestures
  ['wave', '\u{1F44B}'],
  ['raised_back_of_hand', '\u{1F91A}'],
  ['raised_hand', '\u{270B}'],
  ['vulcan_salute', '\u{1F596}'],
  ['ok_hand', '\u{1F44C}'],
  ['pinching_hand', '\u{1F90F}'],
  ['v', '\u{270C}\u{FE0F}'],
  ['crossed_fingers', '\u{1F91E}'],
  ['love_you_gesture', '\u{1F91F}'],
  ['metal', '\u{1F918}'],
  ['call_me_hand', '\u{1F919}'],
  ['point_left', '\u{1F448}'],
  ['point_right', '\u{1F449}'],
  ['point_up', '\u{261D}\u{FE0F}'],
  ['point_down', '\u{1F447}'],
  ['thumbsup', '\u{1F44D}'],
  ['+1', '\u{1F44D}'],
  ['thumbsdown', '\u{1F44E}'],
  ['-1', '\u{1F44E}'],
  ['fist', '\u{270A}'],
  ['fist_right', '\u{1F91C}'],
  ['fist_left', '\u{1F91B}'],
  ['clap', '\u{1F44F}'],
  ['raised_hands', '\u{1F64C}'],
  ['open_hands', '\u{1F450}'],
  ['palms_up_together', '\u{1F932}'],
  ['handshake', '\u{1F91D}'],
  ['pray', '\u{1F64F}'],
  ['muscle', '\u{1F4AA}'],
  ['eyes', '\u{1F440}'],
  ['eye', '\u{1F441}\u{FE0F}'],
  ['tongue', '\u{1F445}'],
  ['lips', '\u{1F444}'],
  ['brain', '\u{1F9E0}'],
  ['baby', '\u{1F476}'],
  ['man', '\u{1F468}'],
  ['woman', '\u{1F469}'],
  ['boy', '\u{1F466}'],
  ['girl', '\u{1F467}'],
  ['person_shrugging', '\u{1F937}'],
  ['shrug', '\u{1F937}'],
  ['person_facepalming', '\u{1F926}'],
  ['facepalm', '\u{1F926}'],

  // Nature & Animals
  ['dog', '\u{1F436}'],
  ['cat', '\u{1F431}'],
  ['mouse', '\u{1F42D}'],
  ['hamster', '\u{1F439}'],
  ['rabbit', '\u{1F430}'],
  ['fox_face', '\u{1F98A}'],
  ['bear', '\u{1F43B}'],
  ['panda_face', '\u{1F43C}'],
  ['koala', '\u{1F428}'],
  ['tiger', '\u{1F42F}'],
  ['lion', '\u{1F981}'],
  ['cow', '\u{1F42E}'],
  ['pig', '\u{1F437}'],
  ['frog', '\u{1F438}'],
  ['monkey_face', '\u{1F435}'],
  ['chicken', '\u{1F414}'],
  ['penguin', '\u{1F427}'],
  ['bird', '\u{1F426}'],
  ['eagle', '\u{1F985}'],
  ['owl', '\u{1F989}'],
  ['bat', '\u{1F987}'],
  ['wolf', '\u{1F43A}'],
  ['horse', '\u{1F434}'],
  ['unicorn', '\u{1F984}'],
  ['bee', '\u{1F41D}'],
  ['bug', '\u{1F41B}'],
  ['butterfly', '\u{1F98B}'],
  ['snail', '\u{1F40C}'],
  ['snake', '\u{1F40D}'],
  ['turtle', '\u{1F422}'],
  ['octopus', '\u{1F419}'],
  ['whale', '\u{1F433}'],
  ['dolphin', '\u{1F42C}'],
  ['fish', '\u{1F41F}'],
  ['shark', '\u{1F988}'],
  ['crab', '\u{1F980}'],
  ['t-rex', '\u{1F996}'],
  ['dragon', '\u{1F409}'],
  ['dragon_face', '\u{1F432}'],
  ['cactus', '\u{1F335}'],
  ['christmas_tree', '\u{1F384}'],
  ['evergreen_tree', '\u{1F332}'],
  ['deciduous_tree', '\u{1F333}'],
  ['palm_tree', '\u{1F334}'],
  ['seedling', '\u{1F331}'],
  ['herb', '\u{1F33F}'],
  ['four_leaf_clover', '\u{1F340}'],
  ['maple_leaf', '\u{1F341}'],
  ['mushroom', '\u{1F344}'],
  ['rose', '\u{1F339}'],
  ['sunflower', '\u{1F33B}'],
  ['cherry_blossom', '\u{1F338}'],
  ['tulip', '\u{1F337}'],

  // Food & Drink
  ['apple', '\u{1F34E}'],
  ['green_apple', '\u{1F34F}'],
  ['banana', '\u{1F34C}'],
  ['grapes', '\u{1F347}'],
  ['watermelon', '\u{1F349}'],
  ['strawberry', '\u{1F353}'],
  ['peach', '\u{1F351}'],
  ['cherry', '\u{1F352}'],
  ['mango', '\u{1F96D}'],
  ['avocado', '\u{1F951}'],
  ['pizza', '\u{1F355}'],
  ['hamburger', '\u{1F354}'],
  ['fries', '\u{1F35F}'],
  ['hotdog', '\u{1F32D}'],
  ['taco', '\u{1F32E}'],
  ['burrito', '\u{1F32F}'],
  ['popcorn', '\u{1F37F}'],
  ['egg', '\u{1F95A}'],
  ['cake', '\u{1F370}'],
  ['birthday', '\u{1F382}'],
  ['cookie', '\u{1F36A}'],
  ['chocolate_bar', '\u{1F36B}'],
  ['candy', '\u{1F36C}'],
  ['lollipop', '\u{1F36D}'],
  ['ice_cream', '\u{1F368}'],
  ['doughnut', '\u{1F369}'],
  ['coffee', '\u{2615}'],
  ['tea', '\u{1F375}'],
  ['beer', '\u{1F37A}'],
  ['beers', '\u{1F37B}'],
  ['wine_glass', '\u{1F377}'],
  ['cocktail', '\u{1F378}'],
  ['champagne', '\u{1F37E}'],

  // Activities & Sports
  ['soccer', '\u{26BD}'],
  ['basketball', '\u{1F3C0}'],
  ['football', '\u{1F3C8}'],
  ['baseball', '\u{26BE}'],
  ['tennis', '\u{1F3BE}'],
  ['volleyball', '\u{1F3D0}'],
  ['rugby_football', '\u{1F3C9}'],
  ['trophy', '\u{1F3C6}'],
  ['medal_sports', '\u{1F3C5}'],
  ['first_place_medal', '\u{1F947}'],
  ['second_place_medal', '\u{1F948}'],
  ['third_place_medal', '\u{1F949}'],
  ['video_game', '\u{1F3AE}'],
  ['joystick', '\u{1F579}\u{FE0F}'],
  ['dart', '\u{1F3AF}'],
  ['bowling', '\u{1F3B3}'],
  ['guitar', '\u{1F3B8}'],
  ['musical_note', '\u{1F3B5}'],
  ['notes', '\u{1F3B6}'],
  ['microphone', '\u{1F3A4}'],
  ['headphones', '\u{1F3A7}'],
  ['art', '\u{1F3A8}'],
  ['performing_arts', '\u{1F3AD}'],
  ['film_projector', '\u{1F4FD}\u{FE0F}'],
  ['tada', '\u{1F389}'],
  ['confetti_ball', '\u{1F38A}'],
  ['balloon', '\u{1F388}'],
  ['gift', '\u{1F381}'],
  ['ribbon', '\u{1F380}'],

  // Travel & Places
  ['car', '\u{1F697}'],
  ['taxi', '\u{1F695}'],
  ['bus', '\u{1F68C}'],
  ['ambulance', '\u{1F691}'],
  ['fire_engine', '\u{1F692}'],
  ['airplane', '\u{2708}\u{FE0F}'],
  ['rocket', '\u{1F680}'],
  ['helicopter', '\u{1F681}'],
  ['ship', '\u{1F6A2}'],
  ['sailboat', '\u{26F5}'],
  ['bike', '\u{1F6B2}'],
  ['house', '\u{1F3E0}'],
  ['office', '\u{1F3E2}'],
  ['hospital', '\u{1F3E5}'],
  ['bank', '\u{1F3E6}'],
  ['tent', '\u{26FA}'],
  ['earth_americas', '\u{1F30E}'],
  ['earth_europe', '\u{1F30D}'],
  ['earth_asia', '\u{1F30F}'],
  ['globe_with_meridians', '\u{1F310}'],
  ['sun_with_face', '\u{1F31E}'],
  ['full_moon_with_face', '\u{1F31D}'],
  ['rainbow', '\u{1F308}'],
  ['cloud', '\u{2601}\u{FE0F}'],
  ['snowflake', '\u{2744}\u{FE0F}'],
  ['umbrella', '\u{2614}'],
  ['ocean', '\u{1F30A}'],
  ['volcano', '\u{1F30B}'],
  ['camping', '\u{1F3D5}\u{FE0F}'],
  ['mount_fuji', '\u{1F5FB}'],

  // Objects
  ['watch', '\u{231A}'],
  ['iphone', '\u{1F4F1}'],
  ['computer', '\u{1F4BB}'],
  ['keyboard', '\u{2328}\u{FE0F}'],
  ['desktop_computer', '\u{1F5A5}\u{FE0F}'],
  ['tv', '\u{1F4FA}'],
  ['camera', '\u{1F4F7}'],
  ['bulb', '\u{1F4A1}'],
  ['flashlight', '\u{1F526}'],
  ['battery', '\u{1F50B}'],
  ['electric_plug', '\u{1F50C}'],
  ['money_with_wings', '\u{1F4B8}'],
  ['dollar', '\u{1F4B5}'],
  ['gem', '\u{1F48E}'],
  ['wrench', '\u{1F527}'],
  ['hammer', '\u{1F528}'],
  ['gear', '\u{2699}\u{FE0F}'],
  ['link', '\u{1F517}'],
  ['paperclip', '\u{1F4CE}'],
  ['scissors', '\u{2702}\u{FE0F}'],
  ['lock', '\u{1F512}'],
  ['unlock', '\u{1F513}'],
  ['key', '\u{1F511}'],
  ['bell', '\u{1F514}'],
  ['no_bell', '\u{1F515}'],
  ['bookmark', '\u{1F516}'],
  ['books', '\u{1F4DA}'],
  ['book', '\u{1F4D6}'],
  ['memo', '\u{1F4DD}'],
  ['pencil2', '\u{270F}\u{FE0F}'],
  ['envelope', '\u{2709}\u{FE0F}'],
  ['email', '\u{1F4E7}'],
  ['inbox_tray', '\u{1F4E5}'],
  ['outbox_tray', '\u{1F4E4}'],
  ['package', '\u{1F4E6}'],
  ['calendar', '\u{1F4C5}'],
  ['chart_with_upwards_trend', '\u{1F4C8}'],
  ['chart_with_downwards_trend', '\u{1F4C9}'],
  ['clipboard', '\u{1F4CB}'],
  ['pushpin', '\u{1F4CC}'],
  ['mag', '\u{1F50D}'],
  ['mag_right', '\u{1F50E}'],

  // Symbols & Flags
  ['white_check_mark', '\u{2705}'],
  ['ballot_box_with_check', '\u{2611}\u{FE0F}'],
  ['heavy_check_mark', '\u{2714}\u{FE0F}'],
  ['x', '\u{274C}'],
  ['negative_squared_cross_mark', '\u{274E}'],
  ['exclamation', '\u{2757}'],
  ['question', '\u{2753}'],
  ['grey_exclamation', '\u{2755}'],
  ['grey_question', '\u{2754}'],
  ['bangbang', '\u{203C}\u{FE0F}'],
  ['interrobang', '\u{2049}\u{FE0F}'],
  ['warning', '\u{26A0}\u{FE0F}'],
  ['no_entry', '\u{26D4}'],
  ['no_entry_sign', '\u{1F6AB}'],
  ['recycle', '\u{267B}\u{FE0F}'],
  ['infinity', '\u{267E}\u{FE0F}'],
  ['arrow_up', '\u{2B06}\u{FE0F}'],
  ['arrow_down', '\u{2B07}\u{FE0F}'],
  ['arrow_left', '\u{2B05}\u{FE0F}'],
  ['arrow_right', '\u{27A1}\u{FE0F}'],
  ['arrow_forward', '\u{25B6}\u{FE0F}'],
  ['arrow_backward', '\u{25C0}\u{FE0F}'],
  ['new', '\u{1F195}'],
  ['free', '\u{1F193}'],
  ['sos', '\u{1F198}'],
  ['information_source', '\u{2139}\u{FE0F}'],
  ['abc', '\u{1F524}'],
  ['1234', '\u{1F522}'],
  ['copyright', '\u{00A9}\u{FE0F}'],
  ['registered', '\u{00AE}\u{FE0F}'],
  ['tm', '\u{2122}\u{FE0F}'],
  ['hash', '\u{0023}\u{20E3}'],
  ['keycap_star', '\u{002A}\u{20E3}'],
  ['zero', '\u{0030}\u{20E3}'],
  ['one', '\u{0031}\u{20E3}'],
  ['two', '\u{0032}\u{20E3}'],
  ['three', '\u{0033}\u{20E3}'],
  ['four', '\u{0034}\u{20E3}'],
  ['five', '\u{0035}\u{20E3}'],
  ['six', '\u{0036}\u{20E3}'],
  ['seven', '\u{0037}\u{20E3}'],
  ['eight', '\u{0038}\u{20E3}'],
  ['nine', '\u{0039}\u{20E3}'],
  ['flag_us', '\u{1F1FA}\u{1F1F8}'],
  ['flag_gb', '\u{1F1EC}\u{1F1E7}'],
  ['flag_fr', '\u{1F1EB}\u{1F1F7}'],
  ['flag_de', '\u{1F1E9}\u{1F1EA}'],
  ['flag_jp', '\u{1F1EF}\u{1F1F5}'],
  ['flag_cn', '\u{1F1E8}\u{1F1F3}'],
  ['flag_kr', '\u{1F1F0}\u{1F1F7}'],
  ['flag_br', '\u{1F1E7}\u{1F1F7}'],
  ['flag_in', '\u{1F1EE}\u{1F1F3}'],
  ['flag_ca', '\u{1F1E8}\u{1F1E6}'],
  ['flag_au', '\u{1F1E6}\u{1F1FA}'],
  ['flag_es', '\u{1F1EA}\u{1F1F8}'],
  ['flag_it', '\u{1F1EE}\u{1F1F9}'],
  ['flag_ru', '\u{1F1F7}\u{1F1FA}'],
  ['flag_mx', '\u{1F1F2}\u{1F1FD}'],
  ['checkered_flag', '\u{1F3C1}'],
  ['triangular_flag_on_post', '\u{1F6A9}'],
  ['pirate_flag', '\u{1F3F4}\u{200D}\u{2620}\u{FE0F}'],
  ['rainbow_flag', '\u{1F3F3}\u{FE0F}\u{200D}\u{1F308}'],
  ['white_flag', '\u{1F3F3}\u{FE0F}'],
]);

// Categorized emoji data for the picker
export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: 'Smileys',
    emojis: [
      'grinning', 'smile', 'grin', 'laughing', 'joy', 'rofl', 'blush',
      'innocent', 'wink', 'smiley', 'heart_eyes', 'star_struck',
      'kissing_heart', 'yum', 'stuck_out_tongue', 'stuck_out_tongue_winking_eye',
      'zany_face', 'hugs', 'thinking', 'shushing_face', 'zipper_mouth_face',
      'neutral_face', 'expressionless', 'smirk', 'unamused', 'roll_eyes',
      'grimacing', 'relieved', 'pensive', 'sleepy', 'sleeping', 'mask',
      'nerd_face', 'sunglasses', 'partying_face', 'confused', 'worried',
      'open_mouth', 'astonished', 'flushed', 'pleading_face', 'cry', 'sob',
      'scream', 'angry', 'rage', 'cursing_face', 'skull', 'poop',
      'clown_face', 'ghost', 'alien', 'robot',
    ].map((s) => ({ shortcode: s, emoji: EMOJI_SHORTCODES.get(s)! })),
  },
  {
    name: 'People',
    emojis: [
      'wave', 'raised_hand', 'ok_hand', 'v', 'crossed_fingers',
      'love_you_gesture', 'metal', 'call_me_hand', 'point_left',
      'point_right', 'point_up', 'point_down', 'thumbsup', 'thumbsdown',
      'fist', 'clap', 'raised_hands', 'open_hands', 'handshake', 'pray',
      'muscle', 'eyes', 'tongue', 'lips', 'brain', 'baby', 'man', 'woman',
      'boy', 'girl', 'shrug', 'facepalm', 'see_no_evil', 'hear_no_evil',
      'speak_no_evil',
    ].map((s) => ({ shortcode: s, emoji: EMOJI_SHORTCODES.get(s)! })),
  },
  {
    name: 'Nature',
    emojis: [
      'dog', 'cat', 'mouse', 'hamster', 'rabbit', 'fox_face', 'bear',
      'panda_face', 'koala', 'tiger', 'lion', 'cow', 'pig', 'frog',
      'monkey_face', 'chicken', 'penguin', 'bird', 'eagle', 'owl', 'bat',
      'wolf', 'horse', 'unicorn', 'bee', 'bug', 'butterfly', 'snail',
      'snake', 'turtle', 'octopus', 'whale', 'dolphin', 'fish', 'shark',
      'crab', 't-rex', 'dragon', 'rose', 'sunflower', 'cherry_blossom',
      'tulip', 'four_leaf_clover', 'maple_leaf', 'mushroom', 'seedling',
      'cactus', 'palm_tree', 'evergreen_tree',
    ].map((s) => ({ shortcode: s, emoji: EMOJI_SHORTCODES.get(s)! })),
  },
  {
    name: 'Food',
    emojis: [
      'apple', 'green_apple', 'banana', 'grapes', 'watermelon', 'strawberry',
      'peach', 'cherry', 'mango', 'avocado', 'pizza', 'hamburger', 'fries',
      'hotdog', 'taco', 'burrito', 'popcorn', 'egg', 'cake', 'birthday',
      'cookie', 'chocolate_bar', 'candy', 'lollipop', 'ice_cream', 'doughnut',
      'coffee', 'tea', 'beer', 'beers', 'wine_glass', 'cocktail', 'champagne',
    ].map((s) => ({ shortcode: s, emoji: EMOJI_SHORTCODES.get(s)! })),
  },
  {
    name: 'Activities',
    emojis: [
      'soccer', 'basketball', 'football', 'baseball', 'tennis', 'volleyball',
      'trophy', 'medal_sports', 'first_place_medal', 'second_place_medal',
      'third_place_medal', 'video_game', 'dart', 'bowling', 'guitar',
      'musical_note', 'notes', 'microphone', 'headphones', 'art',
      'performing_arts', 'tada', 'confetti_ball', 'balloon', 'gift',
      'ribbon',
    ].map((s) => ({ shortcode: s, emoji: EMOJI_SHORTCODES.get(s)! })),
  },
  {
    name: 'Travel',
    emojis: [
      'car', 'taxi', 'bus', 'ambulance', 'fire_engine', 'airplane', 'rocket',
      'helicopter', 'ship', 'sailboat', 'bike', 'house', 'office', 'hospital',
      'tent', 'earth_americas', 'earth_europe', 'earth_asia',
      'globe_with_meridians', 'sun_with_face', 'rainbow', 'cloud',
      'snowflake', 'umbrella', 'ocean', 'volcano', 'camping', 'mount_fuji',
    ].map((s) => ({ shortcode: s, emoji: EMOJI_SHORTCODES.get(s)! })),
  },
  {
    name: 'Objects',
    emojis: [
      'watch', 'iphone', 'computer', 'keyboard', 'desktop_computer', 'tv',
      'camera', 'bulb', 'battery', 'electric_plug', 'money_with_wings',
      'dollar', 'gem', 'wrench', 'hammer', 'gear', 'link', 'lock', 'unlock',
      'key', 'bell', 'bookmark', 'books', 'book', 'memo', 'pencil2',
      'envelope', 'email', 'package', 'calendar', 'clipboard', 'pushpin',
      'mag',
    ].map((s) => ({ shortcode: s, emoji: EMOJI_SHORTCODES.get(s)! })),
  },
  {
    name: 'Symbols',
    emojis: [
      'heart', 'orange_heart', 'yellow_heart', 'green_heart', 'blue_heart',
      'purple_heart', 'black_heart', 'broken_heart', 'sparkling_heart',
      'two_hearts', 'fire', 'star', 'sparkles', 'zap', '100', 'boom',
      'white_check_mark', 'heavy_check_mark', 'x', 'exclamation', 'question',
      'warning', 'no_entry', 'recycle', 'infinity', 'arrow_up', 'arrow_down',
      'arrow_left', 'arrow_right', 'new', 'sos', 'information_source',
    ].map((s) => ({ shortcode: s, emoji: EMOJI_SHORTCODES.get(s)! })),
  },
];

// URL pattern to avoid matching colons inside URLs
const URL_PATTERN = /https?:\/\/[^\s]+/g;

/**
 * Replace :shortcode: patterns with Unicode emoji equivalents.
 * Does not match inside URLs. Unknown shortcodes are left as-is.
 */
export function resolveEmojis(text: string): string {
  if (!text) return text;

  // Find all URL ranges to exclude
  const urlRanges: [number, number][] = [];
  let urlMatch: RegExpExecArray | null;
  URL_PATTERN.lastIndex = 0;
  while ((urlMatch = URL_PATTERN.exec(text)) !== null) {
    urlRanges.push([urlMatch.index, urlMatch.index + urlMatch[0].length]);
  }

  // Replace shortcodes, skipping those inside URLs
  const SHORTCODE_PATTERN = /:([a-zA-Z0-9_+-]+):/g;
  return text.replace(SHORTCODE_PATTERN, (match, code: string, offset: number) => {
    // Check if this match is inside a URL
    for (const [start, end] of urlRanges) {
      if (offset >= start && offset < end) {
        return match;
      }
    }
    const emoji = EMOJI_SHORTCODES.get(code);
    return emoji ?? match;
  });
}

// Pattern for matching Unicode emoji sequences (including combined/variation selectors)
const EMOJI_REGEX =
  /(?:\p{Emoji_Presentation}|\p{Emoji}\uFE0F)(?:\u200D(?:\p{Emoji_Presentation}|\p{Emoji}\uFE0F))*/gu;

/**
 * Split a string into text and emoji segments for rendering.
 * Emoji segments get the `.emoji` CSS class for better sizing.
 */
export function splitTextWithEmojis(text: string): TextSegment[] {
  if (!text) return [];

  const segments: TextSegment[] = [];
  let lastIndex = 0;

  EMOJI_REGEX.lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = EMOJI_REGEX.exec(text)) !== null) {
    // Add preceding text if any
    if (match.index > lastIndex) {
      segments.push({ type: 'text', content: text.slice(lastIndex, match.index) });
    }
    segments.push({ type: 'emoji', content: match[0] });
    lastIndex = match.index + match[0].length;
  }

  // Add remaining text
  if (lastIndex < text.length) {
    segments.push({ type: 'text', content: text.slice(lastIndex) });
  }

  return segments;
}
